- hosts: dbserver
  remote_user: root
  tasks:
    - name: Disabled Frirewalld Server
      service: name=firewalld state=stopped enabled=no

    - name: Disabled Selinux Server
      selinux: state=disabled

    - name: Create Base Yum Repos
      yum_repository:
        name: Base
        description: Base Aliyun repo
        baseurl: http://mirrors.aliyun.com/centos/$releasever/os/$basearch/
        gpgcheck: no

    - name: Create  Epel Yum Repos
      yum_repository:
        name: epel
        description: epel Aliyun repo
        baseurl: http://mirrors.aliyun.com/epel/7/$basearch
        gpgcheck: no

    - name: Installed Base  Packages
      yum: name{{ packages }} state=present
      vars:
        packages:
          - rsync
          - nfs-utils
          - net-tools
          - wget
          - tree
          - lrzsz
          - vim
          - unzip
          - httpd-tools
          - bash-completion
          - iftop
          - glances
          - iotop
          - ntpdate
          - dos2unix
          - telnet
          - nc
          - rsync

    - name: Change Limit  /etc/security/limits.conf
      pam_limits:
        domain: "*"
        limit_type: "{{ item.limit_type }}"
        limit_item: "{{ item.limit_item }}"
        value: "{{ item.value }}"
      with_items:
        - { limit_type: "soft", limit_item: "nofile", value: "100000" }
        - { limit_type: "hard", limit_item: "nofile", value: "100000" }

    - name: Change Sysctl Options
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
      with_items:
        - { "name": "fs.file-max", "value": 6815744 }
        - { "name": "net.ipv4.tcp_tw_reuse", "value": 1 }
        - { "name": "net.ipv4.tcp_tw_recycle", "value": 1 }
        - { "name": "net.ipv4.tcp_fin_timeout", "value": 2 }
        - { "name": "net.ipv4.tcp_syncookies", "value": 1 }
        - { "name": "net.ipv4.tcp_keepalive_time", "value": 600 }
        - { "name": "net.ipv4.tcp_max_syn_backlog", "value": 16384 }
        - { "name": "net.ipv4.tcp_max_tw_buckets", "value": 36000 }
        - { "name": "net.ipv4.route.gc_timeout", "value": 100 }
        - { "name": "net.ipv4.tcp_syn_retries", "value": 1 }
        - { "name": "net.ipv4.tcp_synack_retries", "value": 1 }
        - { "name": "net.core.somaxconn", "value": 16384 }
        - { "name": "net.core.netdev_max_backlog", "value": 16384 }
        - { "name": "net.ipv4.tcp_max_orphans ", "value": 16384 }
      ignore_errors: true

    - name: Make sysctl.conf Effect
      shell: "sysctl -p"
      ignore_errors: true
      changed_when: false

    - name: Server Hostname
      shell: hostnamectl set-hostname {{ansible_default_ipv4.address.split('.')[0]}}_{{ansible_default_ipv4.address.split('.')[1]}}_{{ansible_default_ipv4.address.split('.')[2]}}_{{ansible_default_ipv4.address.split('.')[-1]}}
