- name: Create DB File Directory
  file:
    path: "{{ db_dir }}"
    state: directory

- name: Download MySQL And Unzip
  unarchive: src={{ db_file }} dest={{ db_dir }}  remote_src=yes owner=root group=root

- name: Create DB Data Directory
  file:
    path: "{{ db_dir_data }}"
    state: directory
